export type SceneMetadataId =
  | "DICE-ROLLS"
  | "STATS-VISIBILITY"
  | "SHOW-ITEMS"
;

export const SCENE_DICE_ROLLS_METADATA_ID = "DICE-ROLLS";
export const SCENE_STATS_VISIBILITY_METADATA_ID = "STATS-VISIBILITY";
export const SCENE_SHOW_ITEMS_METADATA_ID = "SHOW-ITEMS";