export type SettingMetadataId =
  | "OFFSET"
  | "BAR-AT-TOP"
  | "NAME-TAGS"
  | "COMPANIONS-SEGMENTS"
  | "STRANGERS-SEGMENTS";

export const SETTINGS_OFFSET_METADATA_ID = "OFFSET";
export const SETTINGS_BAR_AT_TOP_METADATA_ID = "BAR-AT-TOP";
export const SETTINGS_NAME_TAGS_METADATA_ID = "NAME-TAGS";
export const SETTINGS_COMPANIONS_SEGMENTS_METADATA_ID = "COMPANIONS-SEGMENTS";
export const SETTINGS_STRANGERS_SEGMENTS_METADATA_ID = "STRANGERS-SEGMENTS";